### ISSUE TITLE
缺少 getEnvInfoSync

### ISSUE THREAD

**Issue by 1998yyh** [AlwaysLoveme/tt-typings#1]
缺少获取小程序环境信息的类型声明 

文档地址:https://microapp.bytedance.com/docs/zh-CN/mini-app/develop/api/open-interface/env-info/get-env-info-sync

**Comment by AlwaysLoveme** [comment]
> 缺少获取小程序环境信息的类型声明
> 
> 文档地址:https://microapp.bytedance.com/docs/zh-CN/mini-app/develop/api/open-interface/env-info/get-env-info-sync

OK，我抽空加上

**Comment by AlwaysLoveme** [comment]
> 缺少获取小程序环境信息的类型声明
> 
> 文档地址:https://microapp.bytedance.com/docs/zh-CN/mini-app/develop/api/open-interface/env-info/get-env-info-sync

Hi, 此问题已修复，请更新到0.0.8版本
