### ISSUE TITLE
Component缺失pageLifetimes

### ISSUE THREAD

**Issue by julytian** [AlwaysLoveme/tt-typings#2]
文档: [pageLifetimes](https://microapp.bytedance.com/docs/zh-CN/mini-app/develop/guide/custom-component/lifetime/)

**Comment by AlwaysLoveme** [comment]
> 文档: [pageLifetimes](https://microapp.bytedance.com/docs/zh-CN/mini-app/develop/guide/custom-component/lifetime/)

OK , 我周末加上

**Comment by AlwaysLoveme** [comment]
> 文档: [pageLifetimes](https://microapp.bytedance.com/docs/zh-CN/mini-app/develop/guide/custom-component/lifetime/)



我看了下，是有lifetimes 的吖，这么写

```TS
Component({
   lifetimes: {
       ready(){}
   }
})
```
