### ISSUE TITLE
缺少showPrompt类型声明

### ISSUE THREAD

**Issue by WuMrZore** [AlwaysLoveme/tt-typings#3]
showPrompt类型声明也没有么😭

**Comment by AlwaysLoveme** [comment]
> showPrompt

有这个API吗？麻烦发下文档链接呢，文档里面我貌似没有找到有这个方法

**Comment by WuMrZore** [comment]
搞错，那是飞书的，现在飞书都是编译成tt

**Comment by AlwaysLoveme** [comment]
> 搞错，那是飞书的，现在飞书都是编译成tt

那这个就没办法了，字节不支持这个方法
